services:
  lobo-liquibase:
    image: liquibase/liquibase:5.0.2
    container_name: lobo-liquibase

    command: >
      sh -c "
      liquibase
      --url=jdbc:oracle:thin:@//192.168.2.185:1521/XE
      --username=system
      --password=oracle
      --driver=oracle.jdbc.OracleDriver
      --classpath=/liquibase/lib/ojdbc8.jar
      --changeLogFile=changelog.xml
      --log-level=info
      update;
      echo 'Liquibase finished... keeping container alive';
      sleep 300
      "

    volumes:
      - ./config:/liquibase/changelog
      - ./scripts:/liquibase/changelog/scripts
      - ./ojdbc8.jar:/liquibase/lib/ojdbc8.jar

    working_dir: /liquibase/changelog
